# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170505_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='smoker',
            field=models.NullBooleanField(choices=[(None, 'I do not know now'), (True, 'Yes I acknowledge this'), (False, 'No, I do not like this')]),
        ),
    ]
