# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_smoker'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='men_or_women_on_room',
            field=models.NullBooleanField(choices=[(None, "Don't care"), (True, 'Men only'), (False, 'Women only')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoker',
            field=models.NullBooleanField(choices=[(None, "Don't care"), (True, 'Yes'), (False, 'No')]),
        ),
    ]
