# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170505_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prefered_cuisine',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='same_nationality_roommates',
            field=models.NullBooleanField(choices=[(None, "Don't care"), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(choices=[('GR', 'GREEK'), ('FR', 'FRENCH'), ('CHIN', 'CHINESE')], default='', max_length=200),
        ),
    ]
