# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170505_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefered_cuisine',
            field=models.CharField(choices=[('GR', 'GREEK'), ('FR', 'FRENCH'), ('CHIN', 'CHINESE')], default='', max_length=10),
        ),
    ]
