# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170505_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefered_cuisine',
            field=models.CharField(choices=[('GR', 'GREEK'), ('FR', 'FRENCH'), ('CHINESE', 'CHINESE')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='same_nationality_roommates',
            field=models.NullBooleanField(choices=[("Don't care", "Don't care"), ('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoker',
            field=models.NullBooleanField(choices=[("Don't care", "Don't care"), ('Yes', 'Yes'), ('No', 'No')]),
        ),
    ]
