# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170505_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='men_or_women_on_room',
            field=models.NullBooleanField(choices=[("Don't care", "Don't care"), ('Men only', 'Men only'), ('Women only', 'Women only')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoker',
            field=models.NullBooleanField(choices=[("Don't care", "Don't care"), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=10),
        ),
    ]
