# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170505_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_of_people_on_room',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_of_staying_in_flat',
            field=models.CharField(choices=[('1 MONTH', '1 MONTH'), ('2 MONTHS', '2 MONTHS'), ('3 MONTHS', '3 MONTHS'), ('4 MONTHS', '4 MONTHS'), ('5 MONTHS ', '5 MONTHS'), ('6 MONTHS ', '6 MONTHS')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=100),
        ),
    ]
