# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170505_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_of_studies',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_of_studies',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='men_or_women_on_room',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('Men only', 'Men only'), ('Women only', 'Women only')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='num_of_people_on_room',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
